// <auto-generated />
using System;
using DigitalPostal.Api.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DigitalPostal.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260830162132_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DigitalPostal.Api.Domain.Entities.IdempotencyRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ResponseBody")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ResponseStatusCode")
                        .HasColumnType("integer");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SenderId", "Key")
                        .IsUnique();

                    b.ToTable("IdempotencyRecords");
                });

            modelBuilder.Entity("DigitalPostal.Api.Domain.Entities.Letter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CalculationVersion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeliveredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("DistanceKm")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("EstimatedDeliveryAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RecipientId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("SentAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("RecipientId");

                    b.HasIndex("SenderId");

                    b.HasIndex("Status", "EstimatedDeliveryAtUtc");

                    b.ToTable("Letters");
                });

            modelBuilder.Entity("DigitalPostal.Api.Domain.Entities.LetterEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("LetterId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LetterId", "OccurredAtUtc");

                    b.ToTable("LetterEvents");
                });

            modelBuilder.Entity("DigitalPostal.Api.Domain.Entities.LetterStamp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AppliedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LetterEventId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LetterId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StampId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LetterEventId");

                    b.HasIndex("StampId");

                    b.HasIndex("LetterId", "AppliedAtUtc");

                    b.ToTable("LetterStamps");
                });

            modelBuilder.Entity("DigitalPostal.Api.Domain.Entities.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Region")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("DigitalPostal.Api.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LetterId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ReadAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LetterId");

                    b.HasIndex("UserId", "CreatedAtUtc");

                    b.HasIndex("UserId", "ReadAtUtc");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("DigitalPostal.Api.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("DigitalPostal.Api.Domain.Entities.Stamp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LocationId", "IsActive");

                    b.ToTable("Stamps");
                });

            modelBuilder.Entity("DigitalPostal.Api.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CurrentLocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("NormalizedUsername")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("CurrentLocationId");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique();

                    b.HasIndex("NormalizedUsername")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DigitalPostal.Api.Domain.Entities.Letter", b =>
                {
                    b.HasOne("DigitalPostal.Api.Domain.Entities.User", "Recipient")
                        .WithMany()
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DigitalPostal.Api.Domain.Entities.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("DigitalPostal.Api.Domain.ValueObjects.LocationSnapshot", "DestinationLocation", b1 =>
                        {
                            b1.Property<Guid>("LetterId");

                            b1.Property<string>("City")
                                .IsRequired();

                            b1.Property<string>("Country")
                                .IsRequired();

                            b1.Property<string>("CountryCode")
                                .IsRequired();

                            b1.Property<double>("Latitude");

                            b1.Property<double>("Longitude");

                            b1.Property<string>("Region");

                            b1.Property<string>("TimeZone")
                                .IsRequired();

                            b1.HasKey("LetterId");

                            b1.ToTable("Letters");

                            b1
                                .ToJson("DestinationLocation")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("LetterId");
                        });

                    b.OwnsOne("DigitalPostal.Api.Domain.ValueObjects.LocationSnapshot", "OriginLocation", b1 =>
                        {
                            b1.Property<Guid>("LetterId");

                            b1.Property<string>("City")
                                .IsRequired();

                            b1.Property<string>("Country")
                                .IsRequired();

                            b1.Property<string>("CountryCode")
                                .IsRequired();

                            b1.Property<double>("Latitude");

                            b1.Property<double>("Longitude");

                            b1.Property<string>("Region");

                            b1.Property<string>("TimeZone")
                                .IsRequired();

                            b1.HasKey("LetterId");

                            b1.ToTable("Letters");

                            b1
                                .ToJson("OriginLocation")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("LetterId");
                        });

                    b.Navigation("DestinationLocation")
                        .IsRequired();

                    b.Navigation("OriginLocation")
                        .IsRequired();

                    b.Navigation("Recipient");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("DigitalPostal.Api.Domain.Entities.LetterEvent", b =>
                {
                    b.HasOne("DigitalPostal.Api.Domain.Entities.Letter", "Letter")
                        .WithMany("Events")
                        .HasForeignKey("LetterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("DigitalPostal.Api.Domain.ValueObjects.LocationSnapshot", "LocationSnapshot", b1 =>
                        {
                            b1.Property<Guid>("LetterEventId");

                            b1.Property<string>("City")
                                .IsRequired();

                            b1.Property<string>("Country")
                                .IsRequired();

                            b1.Property<string>("CountryCode")
                                .IsRequired();

                            b1.Property<double>("Latitude");

                            b1.Property<double>("Longitude");

                            b1.Property<string>("Region");

                            b1.Property<string>("TimeZone")
                                .IsRequired();

                            b1.HasKey("LetterEventId");

                            b1.ToTable("LetterEvents");

                            b1
                                .ToJson("LocationSnapshot")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("LetterEventId");
                        });

                    b.Navigation("Letter");

                    b.Navigation("LocationSnapshot");
                });

            modelBuilder.Entity("DigitalPostal.Api.Domain.Entities.LetterStamp", b =>
                {
                    b.HasOne("DigitalPostal.Api.Domain.Entities.LetterEvent", "LetterEvent")
                        .WithMany()
                        .HasForeignKey("LetterEventId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DigitalPostal.Api.Domain.Entities.Letter", "Letter")
                        .WithMany("Stamps")
                        .HasForeignKey("LetterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DigitalPostal.Api.Domain.Entities.Stamp", "Stamp")
                        .WithMany()
                        .HasForeignKey("StampId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("DigitalPostal.Api.Domain.ValueObjects.StampSnapshot", "StampSnapshot", b1 =>
                        {
                            b1.Property<Guid>("LetterStampId");

                            b1.Property<string>("ImageUrl")
                                .IsRequired();

                            b1.Property<string>("Name")
                                .IsRequired();

                            b1.Property<int>("Version");

                            b1.HasKey("LetterStampId");

                            b1.ToTable("LetterStamps");

                            b1
                                .ToJson("StampSnapshot")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("LetterStampId");
                        });

                    b.Navigation("Letter");

                    b.Navigation("LetterEvent");

                    b.Navigation("Stamp");

                    b.Navigation("StampSnapshot")
                        .IsRequired();
                });

            modelBuilder.Entity("DigitalPostal.Api.Domain.Entities.Notification", b =>
                {
                    b.HasOne("DigitalPostal.Api.Domain.Entities.Letter", "Letter")
                        .WithMany()
                        .HasForeignKey("LetterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DigitalPostal.Api.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Letter");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DigitalPostal.Api.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("DigitalPostal.Api.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DigitalPostal.Api.Domain.Entities.Stamp", b =>
                {
                    b.HasOne("DigitalPostal.Api.Domain.Entities.Location", "Location")
                        .WithMany("Stamps")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("DigitalPostal.Api.Domain.Entities.User", b =>
                {
                    b.HasOne("DigitalPostal.Api.Domain.Entities.Location", "CurrentLocation")
                        .WithMany()
                        .HasForeignKey("CurrentLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CurrentLocation");
                });

            modelBuilder.Entity("DigitalPostal.Api.Domain.Entities.Letter", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Stamps");
                });

            modelBuilder.Entity("DigitalPostal.Api.Domain.Entities.Location", b =>
                {
                    b.Navigation("Stamps");
                });

            modelBuilder.Entity("DigitalPostal.Api.Domain.Entities.User", b =>
                {
                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
